package org.trnltk.cookbook.spellcheck;

public enum Tolerance {
    ALLOW_PROPER_NOUNS,
    ALLOW_NON_DICTIONARY_NOUNS,
    ALLOW_NON_DICTIONARY_VERBS,
    ALLOW_NON_DICTIONARY_NOUN_COMPOUNDS,
    ALLOW_CONVERSION_OF_CIRCUMFLEXES,
}
